### PR TITLE
Feature/reduce unit tests time

### LINKED ISSUE #7: Reduce unit tests time

### PR DESCRIPTION
**Pull request by yutopp**
Fix #7 .

### CODE REVIEW

**Comment by yutopp** [comment]
- Execute all unit tests in a single Emacs process.
  - Removed loading of the package at for each unit tests to reduce loading time.
- Dropped support for Emacs 24.3 and 24.4  on CI.
  - To use `subr-x` package in unit tests.
- Parallelize executing unit tests is remaining as a task...

**Comment by nomaddo** [comment]
I think `test/generate-diff.el`  should be located in `script`.

**Comment by yutopp** [comment]
`test/generate-diff.el` is used for only testing, not for general purpose. Thus, I think that there is no problem a location of the file is as is.

Are there any guidelines for directory structures for Emacs plugins?

**Comment by nomaddo** [comment]
Let's move `test/generate-diff.el` to `test/script/generate-diff.el`. Then, LGTM

cpiitqgvuaasdk3

**Comment by yutopp** [comment]
done!

**Pull request merged**
