### PR TITLE
Split indent-test

### PR DESCRIPTION
**Pull request by nomaddo**
- [x] split tests
- [x] show coverage
  Currently, `make test` stops if each test failed. It is not useful behavior.

### CODE REVIEW

**Comment by nomaddo** [comment]
Currently, `make test` show its coverage.
But the problem is, it become very slow compare with previous one-file test....

```
$ make test -j
make -C test
make[1]: Entering directory '/home/nomaddo/yuareg/test'
total:  192  success:  181  failed:  11
Makefile:9: recipe for target 'diff-test' failed
make[1]: *** [diff-test] Error 1
make[1]: Leaving directory '/home/nomaddo/yuareg/test'
Makefile:64: recipe for target 'diff-test' failed
make: *** [diff-test] Error 2
```

**Comment by yutopp** [comment]
I think that it is good to reduce unit tests time in an another PR.

So could you resolve conflicts? :pray:

**Comment by nomaddo** [comment]
Ready to be merged!!!

**Comment by yutopp** [comment]
Thanks! LGTM!

**Review by yutopp — APPROVED** [review]

**Comment by yutopp** [comment]
I've created an issue: https://github.com/yutopp/yuareg/issues/7

**Pull request merged**
